ZSH_CONFIG_DIR=$HOME/.config/zsh

# Load zsh config files
for file in $(ls -d $ZSH_CONFIG_DIR/*.zsh); do
	source $file
done

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
