ZSH_CONFIG_DIR=$HOME/.config/zsh

# List of config files, to make sure thay load in correct order
CONFIG_FILES=(
	preset.zsh
	plugins.zsh
	opts.zsh
	aliases.zsh
	keybinds.zsh
	functions.zsh
	history_settings.zsh
	prompt.zsh
	hooks.zsh
    completion.zsh
)

# Load zsh config files
for file in $CONFIG_FILES; do
	source $ZSH_CONFIG_DIR/$file
done

# Load computer specific configuration, if it exists
if [[ -f $ZSH_CONFIG_DIR/custom.zsh ]]; then
	source $ZSH_CONFIG_DIR/custom.zsh
fi
