live_config_reload = true

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[keyboard]
bindings = [
    { key = "Key6", mods = "Control", chars = "\u001E" },
    { key = "Left", mods = "Command", chars = "\u001BOH", mode = "AppCursor" },
    { key = "Right", mods = "Command", chars = "\u001BOF", mode = "AppCursor" },
    { key = "Return", mods = "Control", chars = "\u001B[13;5u" },
]

[scrolling]
history = 100000
multiplier = 3

[shell]
args = ["-l"]
program = "/opt/homebrew/bin/zsh"

[window]
decorations = "full"
dynamic_title = false
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 160
lines = 50
