#!/usr/bin/env bash

set -e

config_pkg=(
    bin
    brew
    ghostty
    git
    mise
    nvim
    tmux
    zsh
)

for pkg in "${config_pkg[@]}"; do
    /opt/homebrew/bin/stow -v --target="${HOME}" "${pkg}"
done
