#!/usr/bin/env zsh

set -a

config=$(cat git/gitconfig)

read "name?Username: "
read "email?Email: "
read "branch?Default branch: "
read "sign?Sign commits? [y/N]: "

if [[ "$sign" =~ ^[Yy]$ ]]; then
    read "signingkey?Signing key (~/.ssh/id_rsa): "
else
    # Delete commit signing configuration
    config=$(sed -e '/\[gpg\]/I,+5 d' -e '/signingkey/d' <<<$config)
fi

envsubst <<<$config |> $HOME/.gitconfig
[[ ! -f $HOME/.gitignore_global ]] && ln -s $(pwd)/git/gitignore_global $HOME/.gitignore_global

# vim:ft=zsh
