#!/usr/bin/env zsh

if [[ -z "$1" ]]; then
    profile=$(aws configure list-profiles | fzf)
else
    profile="$1"
fi

if [[ -z "$profile" ]]; then
    return 1
fi

export GRANTED_ALIAS_CONFIGURED="true"
export GRANTED_QUIET="true"

source assume "$profile"

cluster=$(aws eks list-clusters --no-cli-pager --query 'clusters' --output text | fzf)

if [[ -z "$cluster" ]]; then
    return 1
fi

aws eks update-kubeconfig --name "$cluster"

unset GRANTED_QUIET
