#!/usr/bin/env zsh

if (( ${+aliases[$1]} )); then
    als="${aliases[$1]}"

    if [[ ${#@} -gt 1 ]]; then
        shift
        args="${als} ${@}"
    else
        args="${als}"
    fi
else
    args="${@}"
fi

command watch "${args}"
