return {
	"lukas-reineke/indent-blankline.nvim",
	event = { "BufReadPre", "BufNewFile" },
	enabled = false,
	opts = {
		char = "┆",
		use_treesitter = true,
		use_treesitter_scope = true,
		show_trailing_blankline_indent = true,
		show_first_indent_level = false,
		show_current_context = true,
		show_current_context_start = false,
		show_end_of_line = true,
		filetype_exclude = {
			"lspinfo",
			"lazy",
			"checkhelth",
			"help",
			"man",
			"fugitive",
			"gitcommit",
			"dapui_breakpoints",
			"dapui_scopes",
			"dapui_console",
			"dapui_watches",
			"dapui_stacks",
			"dap-repl",
			"tsplayground",
			"oil",
		},
	},
}
