return {
	"lukas-reineke/indent-blankline.nvim",
	event = { "BufReadPre", "BufNewFile" },
	opts = {
		char = "┆",
		context_char = "│",
		use_treesitter = true,
		show_trailing_blankline_indent = false,
		show_first_indent_level = false,
		show_current_context = true,
		show_current_context_start = false,
		filetype_exclude = {
			"checkhelth",
			"dap-repl",
			"dapui_breakpoints",
			"dapui_console",
			"dapui_scopes",
			"dapui_stacks",
			"dapui_watches",
			"fugitive",
			"gitcommit",
			"help",
			"lazy",
			"lspinfo",
			"man",
			"mason",
			"tsplayground",
			"DressingInput",
		},
	},
}
